// Code generated by hertz generator.

package admin

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkadmininitMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _initadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _modelsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpublicmodelsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createpublicmodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletepublicmodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _disablepublicmodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _enablepublicmodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _model_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpublicmodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatepublicmodelMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _usersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listadminusersMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addadminMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _removeadminMw() []app.HandlerFunc {
	// your code...
	return nil
}
