/*
 * Copyright 2025 ynet-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"bytes"
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"io"
	"net/http"
	"net/url"
	"os"
	"path"
	"strconv"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"

	cozeHandler "github.com/ynet-dev/ynet-studio/backend/api/handler/coze"
	external_knowledge_handler "github.com/ynet-dev/ynet-studio/backend/api/handler/external_knowledge"
	admin "github.com/ynet-dev/ynet-studio/backend/api/router/admin"
	// app_developer_api "github.com/ynet-dev/ynet-studio/backend/api/router/app/developer_api" // 注释掉：与 coze 路由冲突
	coze "github.com/ynet-dev/ynet-studio/backend/api/router/coze"
	embedding "github.com/ynet-dev/ynet-studio/backend/api/router/embedding"
	external_knowledge "github.com/ynet-dev/ynet-studio/backend/api/router/external_knowledge"
	memory_config "github.com/ynet-dev/ynet-studio/backend/api/router/memory_config"
	modelmgr "github.com/ynet-dev/ynet-studio/backend/api/router/modelmgr"
	operationlog "github.com/ynet-dev/ynet-studio/backend/api/router/operationlog"
	rerankRouter "github.com/ynet-dev/ynet-studio/backend/api/router/rerank"
	skill "github.com/ynet-dev/ynet-studio/backend/api/router/skill"
	space "github.com/ynet-dev/ynet-studio/backend/api/router/space"
	statistics "github.com/ynet-dev/ynet-studio/backend/api/router/statistics"
	template_publish "github.com/ynet-dev/ynet-studio/backend/api/router/template_publish"
	workflowmcp "github.com/ynet-dev/ynet-studio/backend/api/router/workflowmcp"
	ynet_agent "github.com/ynet-dev/ynet-studio/backend/api/router/ynet_agent"
	ynet_workflow "github.com/ynet-dev/ynet-studio/backend/api/router/ynet_workflow"
	appuser "github.com/ynet-dev/ynet-studio/backend/application/user"
	userentity "github.com/ynet-dev/ynet-studio/backend/domain/user/entity"
	"github.com/ynet-dev/ynet-studio/backend/pkg/ctxcache"
	"github.com/ynet-dev/ynet-studio/backend/pkg/logs"
	"github.com/ynet-dev/ynet-studio/backend/types/consts"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	// app_developer_api.Register(r) // 注释掉：与 coze.Register 中的路由冲突

	admin.Register(r)

	ynet_agent.Register(r)

	memory_config.Register(r)

	ynet_workflow.Register(r)
	workflowmcp.Register(r)

	statistics.Register(r)

	coze.Register(r)
	embedding.Register(r)
	rerankRouter.Register(r)
	external_knowledge.Register(r)
	modelmgr.Register(r)
	skill.Register(r)
	space.Register(r)
	space.RegisterExportImport(r)
	space.RegisterSync(r)
	space.RegisterRelease(r)
	space.RegisterResync(r)
	space.RegisterConfigureModels(r)
	space.RegisterDiagnose(r)
	operationlog.Register(r)
	// space_member.Register(r) // 已经在space模块中包含了
	template_publish.Register(r)
	// Manually register import/export routes until IDL is regenerated
	manualRegisterImportExport(r)
	manualRegisterExternalKnowledge(r)
	cozeLoopProxyRegister(r)
	cardBackendProxyRegister(r)
	staticFileRegister(r)
}

// cardBackendProxyRegister registers a reverse proxy for the finmall card backend.
// 卡片编辑器(/agent-h5 #/m_cardEditor)依赖 finmall 的 aop-web 卡片系统(IDC*.do)、
// fgw 网关、filestore 资源与 ai-example 接口。测试环境(如 226)只部署了 coze-studio、
// 没有这套后端,这些请求会落到 SPA fallback 返回 index.html,导致卡片功能整体不可用。
// 这里把相关前缀透传到真实卡片后端(默认 agent.finmall.com,可用 YNET_CARD_BACKEND_URL 覆盖),
// 使同源下卡片编辑器与卡片相关接口可直接复用线上卡片后端。
func cardBackendProxyRegister(r *server.Hertz) {
	target := strings.TrimRight(os.Getenv("YNET_CARD_BACKEND_URL"), "/")
	if target == "" {
		target = "https://agent.finmall.com"
	}
	if _, err := url.Parse(target); err != nil {
		logs.Warnf("[cardBackendProxy] Invalid YNET_CARD_BACKEND_URL: %v", err)
		return
	}

	httpClient := &http.Client{Timeout: 60 * time.Second}

	// 需要透传到卡片后端的路径前缀。
	// /agent-h5 是 finmall 卡片编辑器(m_cardEditor)预编译 H5,本仓库无源码,
	// 直接代理到线上,使测试环境也能打开真实卡片编辑器(后续在其 index.html 注入 AI 面板)。
	prefixes := []string{"/aop-web", "/fgw", "/filestore", "/ai-example", "/agent-h5"}

	handler := func(c context.Context, ctx *app.RequestContext) {
		originalPath := string(ctx.Request.URI().Path())
		targetURL := target + originalPath
		if qs := string(ctx.Request.URI().QueryString()); qs != "" {
			targetURL += "?" + qs
		}

		var bodyReader io.Reader
		if body := ctx.Request.Body(); len(body) > 0 {
			bodyReader = bytes.NewReader(body)
		}
		proxyReq, err := http.NewRequestWithContext(c, string(ctx.Method()), targetURL, bodyReader)
		if err != nil {
			ctx.JSON(500, map[string]string{"code": "500", "msg": "card proxy error"})
			return
		}

		// 复制请求头,但丢弃 host/connection 及携带 studio 会话凭证的头
		// (Cookie/Authorization),避免把 studio session 泄露给一方卡片后端。
		ctx.Request.Header.VisitAll(func(key, value []byte) {
			k := string(key)
			switch {
			case strings.EqualFold(k, "host"), strings.EqualFold(k, "connection"),
				strings.EqualFold(k, "cookie"), strings.EqualFold(k, "authorization"):
				return
			default:
				proxyReq.Header.Set(k, string(value))
			}
		})

		resp, err := httpClient.Do(proxyReq)
		if err != nil {
			if fallback, ok := buildAOPReadFallbackResponse(originalPath); ok {
				logs.CtxWarnf(c, "[cardBackendProxy] upstream unavailable for %s, using empty read fallback: %v", originalPath, err)
				ctx.JSON(200, fallback)
				return
			}
			logs.CtxWarnf(c, "[cardBackendProxy] request failed: %v", err)
			ctx.JSON(503, map[string]string{"code": "503", "msg": "card backend unavailable"})
			return
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			logs.CtxWarnf(c, "[cardBackendProxy] read response body failed: %v", err)
			ctx.JSON(503, map[string]string{"code": "503", "msg": "card backend unavailable"})
			return
		}

		if resp.StatusCode >= 500 {
			if fallback, ok := buildAOPReadFallbackResponse(originalPath); ok {
				logs.CtxWarnf(c, "[cardBackendProxy] upstream returned %d for %s, using empty read fallback", resp.StatusCode, originalPath)
				ctx.JSON(200, fallback)
				return
			}
		}

		// 透传响应头,但剥离跨源敏感头:Set-Cookie(防上游往 studio 源种 cookie)、
		// 以及会影响本站安全策略的 CSP/X-Frame/CORS 头;Content-Length 由实际 body 重算。
		for key, values := range resp.Header {
			switch {
			case strings.EqualFold(key, "Content-Length"),
				strings.EqualFold(key, "Set-Cookie"),
				strings.EqualFold(key, "Content-Security-Policy"),
				strings.EqualFold(key, "X-Frame-Options"),
				strings.EqualFold(key, "Access-Control-Allow-Origin"),
				strings.EqualFold(key, "Access-Control-Allow-Credentials"):
				continue
			}
			for _, v := range values {
				ctx.Response.Header.Add(key, v)
			}
		}
		ctx.SetStatusCode(resp.StatusCode)
		ctx.Response.SetBody(body)
	}

	for _, p := range prefixes {
		r.Any(p+"/*path", handler)
	}

	logs.Infof("[cardBackendProxy] card backend proxy enabled: %v -> %s", prefixes, target)
}

func buildAOPReadFallbackResponse(originalPath string) (map[string]any, bool) {
	endpoint := path.Base(originalPath)
	body := map[string]any{}

	switch endpoint {
	case "MCP0003.do", "MCP0010.do":
		body["serviceInfoList"] = []any{}
		body["totalNums"] = 0
		body["totalPages"] = 0
	case "MCP0016.do":
		body["allCount"] = 0
		body["typeEnmuLists"] = []any{}
	case "MCP0004.do":
		body["serviceInfoList"] = []any{}
	case "MCP0009.do":
		body["serviceInfoList"] = []any{}
	case "IDC10001.do", "IDC10030.do":
		body["cardList"] = []any{}
		body["totalNums"] = 0
		body["totalPages"] = 0
	case "IDC10009.do", "IDC10031.do", "IDC10033.do":
		body["cardClassList"] = []any{}
	case "IDC10004.do":
		body["versionList"] = []any{}
	case "IDC10025.do", "IDC10007.do":
		body["cardInfo"] = map[string]any{}
	case "IDC20026.do":
		body["exportTaskLists"] = []any{}
		body["totalNums"] = 0
		body["totalPages"] = 0
	case "IDC20029.do":
		body["importCardList"] = []any{}
		body["totalNums"] = 0
		body["totalPages"] = 0
	default:
		return nil, false
	}

	return map[string]any{
		"code": 0,
		"msg":  "交易成功",
		"header": map[string]any{
			"errorCode": "0",
			"errorMsg":  "交易成功",
		},
		"body": body,
	}, true
}

// staticFileRegister registers web page router.
func staticFileRegister(r *server.Hertz) {
	cwd, err := os.Getwd()
	if err != nil {
		logs.Warnf("[staticFileRegister] Failed to get current working directory: %v", err)
		cwd = os.Getenv("PWD")
	}

	staticFile := path.Join(cwd, "resources/static/index.html")

	// Serve static assets from cwd/resources/static (avoid absolute join)
	r.Static("/static", path.Join(cwd, "resources/static"))
	r.StaticFile("/favicon.png", "./resources/static/favicon.png")
	r.StaticFile("/config.js", path.Join(cwd, "resources/static/config.js"))
	r.StaticFile("/", staticFile)
	r.StaticFile("/sign", staticFile)

	type data struct {
		Code int32  `json:"code"`
		Msg  string `json:"msg"`
	}

	r.NoRoute(func(c context.Context, ctx *app.RequestContext) {
		path := string(ctx.GetRequest().URI().Path())
		if strings.HasPrefix(path, "/api/") ||
			strings.HasPrefix(path, "/v1/") ||
			strings.HasPrefix(path, "/v3/") {
			ctx.JSON(404, data{
				Code: 404,
				Msg:  "not found",
			})
			return
		}

		// index page will show 404 error
		ctx.File(staticFile)
	})

}

// cozeLoopProxyRegister registers a reverse proxy for Ynet Loop.
// All requests to /loop/* are forwarded to the Ynet Loop backend,
// so the observability UI can be accessed through the same port (8888).
func cozeLoopProxyRegister(r *server.Hertz) {
	cozeLoopURL := os.Getenv("YNET_LOOP_PROXY_URL")
	if cozeLoopURL == "" {
		cozeLoopURL = os.Getenv("YNET_LOOP_TELEMETRY_ENDPOINT")
		if cozeLoopURL != "" {
			// Extract base URL from endpoint like "http://10.10.10.226:8082/v1/loop/opentelemetry/v1/traces"
			if u, err := url.Parse(cozeLoopURL); err == nil {
				cozeLoopURL = u.Scheme + "://" + u.Host
			}
		}
	}
	if cozeLoopURL == "" {
		logs.Infof("[cozeLoopProxy] YNET_LOOP_PROXY_URL not set, skipping Ynet Loop proxy")
		return
	}

	if _, err := url.Parse(cozeLoopURL); err != nil {
		logs.Warnf("[cozeLoopProxy] Invalid YNET_LOOP_PROXY_URL: %v", err)
		return
	}

	httpClient := &http.Client{Timeout: 60 * time.Second}

	// 可信来源白名单（逗号分隔），用于 CORS 收敛；为空时仅放行同源请求。
	loopAllowedOrigins := parseAllowedOrigins(os.Getenv("YNET_LOOP_ALLOWED_ORIGINS"))

	logs.Infof("[cozeLoopProxy] Ynet Loop proxy enabled: /loop/* -> %s", cozeLoopURL)

	// Handle /loop/* - strip /loop prefix and forward to Ynet Loop
	r.Any("/loop/*path", func(c context.Context, ctx *app.RequestContext) {
		// Strip /loop prefix: /loop/api/xxx -> /api/xxx, /loop/console/xxx -> /console/xxx
		originalPath := string(ctx.Request.URI().Path())
		newPath := strings.TrimPrefix(originalPath, "/loop")
		if newPath == "" {
			newPath = "/"
		}

		// Build target URL
		targetURL := cozeLoopURL + newPath
		queryString := string(ctx.Request.URI().QueryString())
		if queryString != "" {
			targetURL += "?" + queryString
		}

		// Create proxy request — use Body() bytes instead of BodyStream()
		// because Hertz may have already consumed the stream
		body := ctx.Request.Body()
		var bodyReader io.Reader
		if len(body) > 0 {
			bodyReader = bytes.NewReader(body)
		}
		proxyReq, err := http.NewRequestWithContext(c,
			string(ctx.Method()), targetURL, bodyReader)
		if err != nil {
			ctx.JSON(500, map[string]string{"code": "500", "msg": "proxy error"})
			return
		}

		// Copy request headers
		ctx.Request.Header.VisitAll(func(key, value []byte) {
			k := string(key)
			if !strings.EqualFold(k, "host") && !strings.EqualFold(k, "connection") && !isLoopInternalIdentityHeader(k) {
				proxyReq.Header.Set(k, string(value))
			}
		})

		// Inject CozeLoop authentication
		if token := os.Getenv("YNET_LOOP_TELEMETRY_TOKEN"); token != "" {
			proxyReq.Header.Set("Authorization", "Bearer "+token)
		}
		// Prefer the current browser session. Loop now accepts Studio-signed
		// session_key cookies, while the static fallback may expire silently.
		if cookieHeader, changed := buildLoopProxyCookieHeader(
			proxyReq.Header.Get("Cookie"),
			os.Getenv("YNET_LOOP_SESSION_KEY"),
		); changed {
			proxyReq.Header.Set("Cookie", cookieHeader)
		}
		if identity, ok := buildLoopInternalIdentity(c, ctx, queryString, proxyReq.Header, body); ok {
			if !setLoopInternalIdentityHeaders(proxyReq.Header, identity, loopInternalAuthSecret()) {
				logs.CtxWarnf(c, "[cozeLoopProxy] skipped internal identity headers: missing user id or shared secret")
			}
		}

		// Forward request
		resp, err := httpClient.Do(proxyReq)
		if err != nil {
			logs.CtxWarnf(c, "[cozeLoopProxy] request failed: %v", err)
			writeLoopUnavailable(ctx, err)
			return
		}
		defer resp.Body.Close()

		// Read the full response body (needed for potential HTML rewriting)
		respBody, err := io.ReadAll(resp.Body)
		if err != nil {
			logs.CtxWarnf(c, "[cozeLoopProxy] read response body failed: %v", err)
			writeLoopUnavailable(ctx, err)
			return
		}

		// For HTML responses, rewrite paths and inject base path configuration
		contentType := resp.Header.Get("Content-Type")
		if strings.Contains(contentType, "text/html") {
			respBody = rewriteCozeLoopHTML(respBody)
		}

		// Copy response headers (skip Content-Length as body size may change after rewriting)
		for key, values := range resp.Header {
			if strings.EqualFold(key, "Content-Length") {
				continue
			}
			for _, v := range values {
				ctx.Response.Header.Add(key, v)
			}
		}

		// Set CORS headers for iframe access, restricted to a trusted origin whitelist
		// instead of "*" so credentials are not exposed to arbitrary origins.
		if origin := string(ctx.Request.Header.Peek("Origin")); origin != "" && isAllowedLoopOrigin(origin, loopAllowedOrigins, ctx) {
			ctx.Response.Header.Set("Access-Control-Allow-Origin", origin)
			ctx.Response.Header.Set("Access-Control-Allow-Credentials", "true")
			ctx.Response.Header.Add("Vary", "Origin")
		}
		ctx.Response.Header.Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		ctx.Response.Header.Set("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Requested-With")

		// Set status code and rewritten body
		ctx.SetStatusCode(resp.StatusCode)
		ctx.Response.SetBody(respBody)
	})
}

func buildLoopProxyCookieHeader(inboundCookie, fallbackSessionKey string) (string, bool) {
	inboundCookie = strings.TrimSpace(inboundCookie)
	fallbackSessionKey = strings.TrimSpace(fallbackSessionKey)
	if fallbackSessionKey == "" || cookieHeaderHasName(inboundCookie, "session_key") {
		return inboundCookie, false
	}
	if inboundCookie == "" {
		return "session_key=" + fallbackSessionKey, true
	}
	return inboundCookie + "; session_key=" + fallbackSessionKey, true
}

const (
	loopInternalHeaderUserID    = "X-Ynet-Studio-User-Id"
	loopInternalHeaderSpaceID   = "X-Ynet-Studio-Space-Id"
	loopInternalHeaderEmail     = "X-Ynet-Studio-Email"
	loopInternalHeaderName      = "X-Ynet-Studio-Name"
	loopInternalHeaderTimestamp = "X-Ynet-Studio-Timestamp"
	loopInternalHeaderSignature = "X-Ynet-Studio-Signature"
)

type loopInternalIdentity struct {
	UserID    string
	SpaceID   string
	Email     string
	Name      string
	Timestamp int64
}

func buildLoopInternalIdentity(
	c context.Context,
	ctx *app.RequestContext,
	queryString string,
	headers http.Header,
	body []byte,
) (loopInternalIdentity, bool) {
	userID := ""
	if session, ok := ctxcache.Get[*userentity.Session](c, consts.SessionDataKeyInCtx); ok && session != nil && session.UserID > 0 {
		userID = strconv.FormatInt(session.UserID, 10)
	}
	if userID == "" {
		sessionKey := string(ctx.Cookie(userentity.SessionKey))
		if sessionKey != "" {
			if session, err := appuser.UserApplicationSVC.ValidateSession(c, sessionKey); err == nil && session != nil && session.UserID > 0 {
				userID = strconv.FormatInt(session.UserID, 10)
			} else if err != nil {
				logs.CtxWarnf(c, "[cozeLoopProxy] validate studio session for Loop identity failed: %v", err)
			}
		}
	}
	if userID == "" {
		return loopInternalIdentity{}, false
	}

	return loopInternalIdentity{
		UserID:  userID,
		SpaceID: extractLoopProxySpaceID(queryString, headers, body, string(ctx.Request.Header.Peek("Referer"))),
	}, true
}

func loopInternalAuthSecret() string {
	if v := strings.TrimSpace(os.Getenv("YNET_LOOP_INTERNAL_AUTH_SECRET")); v != "" {
		return v
	}
	return strings.TrimSpace(os.Getenv("SESSION_HMAC_SECRET"))
}

func setLoopInternalIdentityHeaders(headers http.Header, identity loopInternalIdentity, secret string) bool {
	identity.UserID = strings.TrimSpace(identity.UserID)
	secret = strings.TrimSpace(secret)
	if identity.UserID == "" || secret == "" {
		return false
	}
	if identity.Timestamp == 0 {
		identity.Timestamp = time.Now().Unix()
	}

	headers.Set(loopInternalHeaderUserID, identity.UserID)
	headers.Set(loopInternalHeaderSpaceID, strings.TrimSpace(identity.SpaceID))
	headers.Set(loopInternalHeaderEmail, strings.TrimSpace(identity.Email))
	headers.Set(loopInternalHeaderName, strings.TrimSpace(identity.Name))
	headers.Set(loopInternalHeaderTimestamp, strconv.FormatInt(identity.Timestamp, 10))
	headers.Set(loopInternalHeaderSignature, signLoopInternalIdentity(identity, secret))
	return true
}

func signLoopInternalIdentity(identity loopInternalIdentity, secret string) string {
	mac := hmac.New(sha256.New, []byte(secret))
	mac.Write([]byte(loopInternalIdentityPayload(identity)))
	return hex.EncodeToString(mac.Sum(nil))
}

func loopInternalIdentityPayload(identity loopInternalIdentity) string {
	return strings.Join([]string{
		strings.TrimSpace(identity.UserID),
		strings.TrimSpace(identity.SpaceID),
		strings.TrimSpace(identity.Email),
		strings.TrimSpace(identity.Name),
		strconv.FormatInt(identity.Timestamp, 10),
	}, "\n")
}

func isLoopInternalIdentityHeader(name string) bool {
	switch {
	case strings.EqualFold(name, loopInternalHeaderUserID),
		strings.EqualFold(name, loopInternalHeaderSpaceID),
		strings.EqualFold(name, loopInternalHeaderEmail),
		strings.EqualFold(name, loopInternalHeaderName),
		strings.EqualFold(name, loopInternalHeaderTimestamp),
		strings.EqualFold(name, loopInternalHeaderSignature):
		return true
	default:
		return false
	}
}

func extractLoopProxySpaceID(queryString string, _ http.Header, body []byte, referer string) string {
	if values, err := url.ParseQuery(queryString); err == nil {
		for _, key := range []string{"workspace_id", "space_id"} {
			if id := normalizeLoopNumericID(values.Get(key)); id != "" {
				return id
			}
		}
	}
	if id := extractLoopProxySpaceIDFromJSON(body); id != "" {
		return id
	}
	return extractLoopProxySpaceIDFromReferer(referer)
}

func extractLoopProxySpaceIDFromJSON(body []byte) string {
	if len(body) == 0 {
		return ""
	}
	decoder := json.NewDecoder(bytes.NewReader(body))
	decoder.UseNumber()
	var payload map[string]any
	if err := decoder.Decode(&payload); err != nil {
		return ""
	}
	for _, key := range []string{"workspace_id", "space_id"} {
		if id := normalizeLoopIDValue(payload[key]); id != "" {
			return id
		}
	}
	return ""
}

func normalizeLoopIDValue(value any) string {
	switch v := value.(type) {
	case string:
		return normalizeLoopNumericID(v)
	case json.Number:
		return normalizeLoopNumericID(v.String())
	default:
		return ""
	}
}

func extractLoopProxySpaceIDFromReferer(referer string) string {
	const marker = "/space/"
	idx := strings.Index(referer, marker)
	if idx < 0 {
		return ""
	}
	rest := referer[idx+len(marker):]
	if end := strings.IndexByte(rest, '/'); end >= 0 {
		rest = rest[:end]
	}
	if query := strings.IndexByte(rest, '?'); query >= 0 {
		rest = rest[:query]
	}
	return normalizeLoopNumericID(rest)
}

func normalizeLoopNumericID(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	for _, ch := range value {
		if ch < '0' || ch > '9' {
			return ""
		}
	}
	return value
}

func cookieHeaderHasName(cookieHeader, name string) bool {
	for _, part := range strings.Split(cookieHeader, ";") {
		pair := strings.TrimSpace(part)
		if pair == "" {
			continue
		}
		key, _, ok := strings.Cut(pair, "=")
		if ok && strings.EqualFold(strings.TrimSpace(key), name) {
			return true
		}
	}
	return false
}

// writeLoopUnavailable 在 Ynet Loop 上游不可用时返回优雅降级响应：
// 浏览器页面导航返回简洁的中文 HTML 提示页,API/XHR 请求返回 503 JSON。
// 统一带上 Retry-After 提示客户端稍后重试。
func writeLoopUnavailable(ctx *app.RequestContext, cause error) {
	ctx.Response.Header.Set("Retry-After", "10")
	accept := string(ctx.Request.Header.Peek("Accept"))
	if strings.Contains(accept, "text/html") {
		ctx.SetStatusCode(503)
		ctx.Response.Header.Set("Content-Type", "text/html; charset=utf-8")
		ctx.Response.SetBody([]byte(`<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><title>服务暂时不可用</title></head>` +
			`<body style="font-family:sans-serif;text-align:center;padding:80px"><h2>可观测性服务暂时不可用</h2>` +
			`<p>Ynet Loop 上游连接失败,请稍后重试。</p></body></html>`))
		return
	}
	ctx.JSON(503, map[string]string{"code": "503", "msg": "loop upstream unavailable"})
}

// parseAllowedOrigins 解析逗号分隔的来源白名单为集合。
func parseAllowedOrigins(raw string) map[string]struct{} {
	set := make(map[string]struct{})
	for _, o := range strings.Split(raw, ",") {
		o = strings.TrimSpace(o)
		if o != "" {
			set[o] = struct{}{}
		}
	}
	return set
}

// isAllowedLoopOrigin 判断请求 Origin 是否可信：在白名单内，或与请求自身同源。
func isAllowedLoopOrigin(origin string, allowed map[string]struct{}, ctx *app.RequestContext) bool {
	if _, ok := allowed[origin]; ok {
		return true
	}
	// 同源放行：Origin 的 host 与请求 Host 一致（iframe 同端口嵌入场景）。
	if u, err := url.Parse(origin); err == nil && u.Host != "" {
		if u.Host == string(ctx.Host()) {
			return true
		}
	}
	return false
}

// rewriteCozeLoopHTML rewrites the Ynet Loop SPA HTML to work under the /loop/ subpath.
// It rewrites static asset paths and injects JavaScript to handle API URL rewriting
// and SPA router compatibility.
func rewriteCozeLoopHTML(body []byte) []byte {
	html := string(body)

	// Rewrite static asset paths: /static/ -> /loop/static/
	html = strings.ReplaceAll(html, `src="/static/`, `src="/loop/static/`)
	html = strings.ReplaceAll(html, `href="/static/`, `href="/loop/static/`)
	html = strings.ReplaceAll(html, `href="/coze.svg"`, `href="/loop/coze.svg"`)

	// Inject base path configuration script before the first <script> tag.
	// This script runs before the SPA code and:
	// 1. Strips the /loop prefix from the URL so the SPA router matches routes correctly
	// 2. Overrides fetch/XMLHttpRequest to add /loop prefix to API calls
	// 3. Sets webpack/rspack public path for dynamic chunk loading
	basePathScript := `<script>
(function(){
  var B='/loop';
  if(location.pathname.indexOf(B)===0){
    var p=location.pathname.substring(B.length)||'/';
    history.replaceState(null,'',p+location.search+location.hash);
  }
  var _f=window.fetch;
  window.fetch=function(u,o){
    if(typeof u==='string'&&(u.indexOf('/api/')===0||u.indexOf('/v1/')===0))u=B+u;
    return _f.call(this,u,o);
  };
  var _x=XMLHttpRequest.prototype.open;
  XMLHttpRequest.prototype.open=function(m,u){
    if(typeof u==='string'&&(u.indexOf('/api/')===0||u.indexOf('/v1/')===0))arguments[1]=B+u;
    return _x.apply(this,arguments);
  };
  try{__webpack_public_path__=B+'/';}catch(e){}
})();
</script>
`
	html = strings.Replace(html, "<script", basePathScript+"<script", 1)

	return []byte(html)
}

// manualRegisterImportExport manually registers import/export routes
// TODO: Remove this when IDL is regenerated with import/export definitions
func manualRegisterImportExport(r *server.Hertz) {
	api := r.Group("/api")
	workflowAPI := api.Group("/workflow_api")

	// Register import/export routes
	workflowAPI.POST("/export", cozeHandler.ExportWorkflow)
	workflowAPI.POST("/import", cozeHandler.ImportWorkflow)
	workflowAPI.POST("/validate_import", cozeHandler.ValidateImport)

}

func manualRegisterExternalKnowledge(r *server.Hertz) {
	api := r.Group("/api")
	externalKnowledgeGroup := api.Group("/external-knowledge")
	ragflowGroup := externalKnowledgeGroup.Group("/ragflow")
	ragflowGroup.POST("/datasets/create", external_knowledge_handler.CreateRAGFlowDataset)
	ragflowGroup.POST("/datasets/update", external_knowledge_handler.UpdateRAGFlowDataset)
	ragflowGroup.POST("/datasets/delete", external_knowledge_handler.DeleteRAGFlowDataset)
	ragflowGroup.GET("/session-key", external_knowledge_handler.GetRAGFlowSessionKey)

	knowledgeGroup := api.Group("/knowledge")
	knowledgeGroup.POST("/retrieve_test", cozeHandler.RetrieveTest)
}
