/*
 * Copyright 2025 ynet-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"os"
	"path"
	"strings"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"

	cozeHandler "github.com/ynet-dev/ynet-studio/backend/api/handler/coze"
	external_knowledge_handler "github.com/ynet-dev/ynet-studio/backend/api/handler/external_knowledge"
	admin "github.com/ynet-dev/ynet-studio/backend/api/router/admin"
	// app_developer_api "github.com/ynet-dev/ynet-studio/backend/api/router/app/developer_api" // 注释掉：与 coze 路由冲突
	coze "github.com/ynet-dev/ynet-studio/backend/api/router/coze"
	embedding "github.com/ynet-dev/ynet-studio/backend/api/router/embedding"
	external_knowledge "github.com/ynet-dev/ynet-studio/backend/api/router/external_knowledge"
	rerankRouter "github.com/ynet-dev/ynet-studio/backend/api/router/rerank"
	memory_config "github.com/ynet-dev/ynet-studio/backend/api/router/memory_config"
	modelmgr "github.com/ynet-dev/ynet-studio/backend/api/router/modelmgr"
	skill "github.com/ynet-dev/ynet-studio/backend/api/router/skill"
	space "github.com/ynet-dev/ynet-studio/backend/api/router/space"
	statistics "github.com/ynet-dev/ynet-studio/backend/api/router/statistics"
	template_publish "github.com/ynet-dev/ynet-studio/backend/api/router/template_publish"
	ynet_agent "github.com/ynet-dev/ynet-studio/backend/api/router/ynet_agent"
	ynet_workflow "github.com/ynet-dev/ynet-studio/backend/api/router/ynet_workflow"
	"github.com/ynet-dev/ynet-studio/backend/pkg/logs"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!

	// app_developer_api.Register(r) // 注释掉：与 coze.Register 中的路由冲突

	admin.Register(r)

	ynet_agent.Register(r)

	memory_config.Register(r)

	ynet_workflow.Register(r)

	statistics.Register(r)

	coze.Register(r)
	embedding.Register(r)
	rerankRouter.Register(r)
	external_knowledge.Register(r)
	modelmgr.Register(r)
	skill.Register(r)
	space.Register(r)
	space.RegisterExportImport(r)
	space.RegisterSync(r)
	space.RegisterRelease(r)
	space.RegisterResync(r)
	space.RegisterConfigureModels(r)
	space.RegisterDiagnose(r)
	// space_member.Register(r) // 已经在space模块中包含了
	template_publish.Register(r)
	// Manually register import/export routes until IDL is regenerated
	manualRegisterImportExport(r)
	manualRegisterExternalKnowledge(r)
	cozeLoopProxyRegister(r)
	staticFileRegister(r)
}

// staticFileRegister registers web page router.
func staticFileRegister(r *server.Hertz) {
	cwd, err := os.Getwd()
	if err != nil {
		logs.Warnf("[staticFileRegister] Failed to get current working directory: %v", err)
		cwd = os.Getenv("PWD")
	}

	staticFile := path.Join(cwd, "resources/static/index.html")

	// Serve static assets from cwd/resources/static (avoid absolute join)
	r.Static("/static", path.Join(cwd, "resources/static"))
	r.StaticFile("/favicon.png", "./resources/static/favicon.png")
	r.StaticFile("/config.js", path.Join(cwd, "resources/static/config.js"))
	r.StaticFile("/", staticFile)
	r.StaticFile("/sign", staticFile)

	type data struct {
		Code int32  `json:"code"`
		Msg  string `json:"msg"`
	}

	r.NoRoute(func(c context.Context, ctx *app.RequestContext) {
		path := string(ctx.GetRequest().URI().Path())
		if strings.HasPrefix(path, "/api/") ||
			strings.HasPrefix(path, "/v1/") ||
			strings.HasPrefix(path, "/v3/") {
			ctx.JSON(404, data{
				Code: 404,
				Msg:  "not found",
			})
			return
		}

		// index page will show 404 error
		ctx.File(staticFile)
	})

}

// cozeLoopProxyRegister registers a reverse proxy for Ynet Loop.
// All requests to /loop/* are forwarded to the Ynet Loop backend,
// so the observability UI can be accessed through the same port (8888).
func cozeLoopProxyRegister(r *server.Hertz) {
	cozeLoopURL := os.Getenv("YNET_LOOP_PROXY_URL")
	if cozeLoopURL == "" {
		cozeLoopURL = os.Getenv("YNET_LOOP_TELEMETRY_ENDPOINT")
		if cozeLoopURL != "" {
			// Extract base URL from endpoint like "http://10.10.10.226:8082/v1/loop/opentelemetry/v1/traces"
			if u, err := url.Parse(cozeLoopURL); err == nil {
				cozeLoopURL = u.Scheme + "://" + u.Host
			}
		}
	}
	if cozeLoopURL == "" {
		logs.Infof("[cozeLoopProxy] YNET_LOOP_PROXY_URL not set, skipping Ynet Loop proxy")
		return
	}

	if _, err := url.Parse(cozeLoopURL); err != nil {
		logs.Warnf("[cozeLoopProxy] Invalid YNET_LOOP_PROXY_URL: %v", err)
		return
	}

	httpClient := &http.Client{Timeout: 60 * time.Second}

	// 可信来源白名单（逗号分隔），用于 CORS 收敛；为空时仅放行同源请求。
	loopAllowedOrigins := parseAllowedOrigins(os.Getenv("YNET_LOOP_ALLOWED_ORIGINS"))

	logs.Infof("[cozeLoopProxy] Ynet Loop proxy enabled: /loop/* -> %s", cozeLoopURL)

	// Handle /loop/* - strip /loop prefix and forward to Ynet Loop
	r.Any("/loop/*path", func(c context.Context, ctx *app.RequestContext) {
		// Strip /loop prefix: /loop/api/xxx -> /api/xxx, /loop/console/xxx -> /console/xxx
		originalPath := string(ctx.Request.URI().Path())
		newPath := strings.TrimPrefix(originalPath, "/loop")
		if newPath == "" {
			newPath = "/"
		}

		// Build target URL
		targetURL := cozeLoopURL + newPath
		queryString := string(ctx.Request.URI().QueryString())
		if queryString != "" {
			targetURL += "?" + queryString
		}

		// Create proxy request — use Body() bytes instead of BodyStream()
		// because Hertz may have already consumed the stream
		var bodyReader io.Reader
		if body := ctx.Request.Body(); len(body) > 0 {
			bodyReader = bytes.NewReader(body)
		}
		proxyReq, err := http.NewRequestWithContext(c,
			string(ctx.Method()), targetURL, bodyReader)
		if err != nil {
			ctx.JSON(500, map[string]string{"code": "500", "msg": "proxy error"})
			return
		}

		// Copy request headers
		ctx.Request.Header.VisitAll(func(key, value []byte) {
			k := string(key)
			if !strings.EqualFold(k, "host") && !strings.EqualFold(k, "connection") {
				proxyReq.Header.Set(k, string(value))
			}
		})

		// Inject CozeLoop authentication
		if token := os.Getenv("YNET_LOOP_TELEMETRY_TOKEN"); token != "" {
			proxyReq.Header.Set("Authorization", "Bearer "+token)
		}
		// Inject Loop session cookie for API requests that require session auth
		if sessionKey := os.Getenv("YNET_LOOP_SESSION_KEY"); sessionKey != "" {
			proxyReq.AddCookie(&http.Cookie{Name: "session_key", Value: sessionKey})
		}

		// Forward request
		resp, err := httpClient.Do(proxyReq)
		if err != nil {
			logs.CtxWarnf(c, "[cozeLoopProxy] request failed: %v", err)
			writeLoopUnavailable(ctx, err)
			return
		}
		defer resp.Body.Close()

		// Read the full response body (needed for potential HTML rewriting)
		body, err := io.ReadAll(resp.Body)
		if err != nil {
			logs.CtxWarnf(c, "[cozeLoopProxy] read response body failed: %v", err)
			writeLoopUnavailable(ctx, err)
			return
		}

		// For HTML responses, rewrite paths and inject base path configuration
		contentType := resp.Header.Get("Content-Type")
		if strings.Contains(contentType, "text/html") {
			body = rewriteCozeLoopHTML(body)
		}

		// Copy response headers (skip Content-Length as body size may change after rewriting)
		for key, values := range resp.Header {
			if strings.EqualFold(key, "Content-Length") {
				continue
			}
			for _, v := range values {
				ctx.Response.Header.Add(key, v)
			}
		}

		// Set CORS headers for iframe access, restricted to a trusted origin whitelist
		// instead of "*" so credentials are not exposed to arbitrary origins.
		if origin := string(ctx.Request.Header.Peek("Origin")); origin != "" && isAllowedLoopOrigin(origin, loopAllowedOrigins, ctx) {
			ctx.Response.Header.Set("Access-Control-Allow-Origin", origin)
			ctx.Response.Header.Set("Access-Control-Allow-Credentials", "true")
			ctx.Response.Header.Add("Vary", "Origin")
		}
		ctx.Response.Header.Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		ctx.Response.Header.Set("Access-Control-Allow-Headers", "Content-Type, Authorization, X-Requested-With")

		// Set status code and rewritten body
		ctx.SetStatusCode(resp.StatusCode)
		ctx.Response.SetBody(body)
	})
}

// writeLoopUnavailable 在 Ynet Loop 上游不可用时返回优雅降级响应：
// 浏览器页面导航返回简洁的中文 HTML 提示页,API/XHR 请求返回 503 JSON。
// 统一带上 Retry-After 提示客户端稍后重试。
func writeLoopUnavailable(ctx *app.RequestContext, cause error) {
	ctx.Response.Header.Set("Retry-After", "10")
	accept := string(ctx.Request.Header.Peek("Accept"))
	if strings.Contains(accept, "text/html") {
		ctx.SetStatusCode(503)
		ctx.Response.Header.Set("Content-Type", "text/html; charset=utf-8")
		ctx.Response.SetBody([]byte(`<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><title>服务暂时不可用</title></head>` +
			`<body style="font-family:sans-serif;text-align:center;padding:80px"><h2>可观测性服务暂时不可用</h2>` +
			`<p>Ynet Loop 上游连接失败,请稍后重试。</p></body></html>`))
		return
	}
	ctx.JSON(503, map[string]string{"code": "503", "msg": "loop upstream unavailable"})
}

// parseAllowedOrigins 解析逗号分隔的来源白名单为集合。
func parseAllowedOrigins(raw string) map[string]struct{} {
	set := make(map[string]struct{})
	for _, o := range strings.Split(raw, ",") {
		o = strings.TrimSpace(o)
		if o != "" {
			set[o] = struct{}{}
		}
	}
	return set
}

// isAllowedLoopOrigin 判断请求 Origin 是否可信：在白名单内，或与请求自身同源。
func isAllowedLoopOrigin(origin string, allowed map[string]struct{}, ctx *app.RequestContext) bool {
	if _, ok := allowed[origin]; ok {
		return true
	}
	// 同源放行：Origin 的 host 与请求 Host 一致（iframe 同端口嵌入场景）。
	if u, err := url.Parse(origin); err == nil && u.Host != "" {
		if u.Host == string(ctx.Host()) {
			return true
		}
	}
	return false
}

// rewriteCozeLoopHTML rewrites the Ynet Loop SPA HTML to work under the /loop/ subpath.
// It rewrites static asset paths and injects JavaScript to handle API URL rewriting
// and SPA router compatibility.
func rewriteCozeLoopHTML(body []byte) []byte {
	html := string(body)

	// Rewrite static asset paths: /static/ -> /loop/static/
	html = strings.ReplaceAll(html, `src="/static/`, `src="/loop/static/`)
	html = strings.ReplaceAll(html, `href="/static/`, `href="/loop/static/`)
	html = strings.ReplaceAll(html, `href="/coze.svg"`, `href="/loop/coze.svg"`)

	// Inject base path configuration script before the first <script> tag.
	// This script runs before the SPA code and:
	// 1. Strips the /loop prefix from the URL so the SPA router matches routes correctly
	// 2. Overrides fetch/XMLHttpRequest to add /loop prefix to API calls
	// 3. Sets webpack/rspack public path for dynamic chunk loading
	basePathScript := `<script>
(function(){
  var B='/loop';
  if(location.pathname.indexOf(B)===0){
    var p=location.pathname.substring(B.length)||'/';
    history.replaceState(null,'',p+location.search+location.hash);
  }
  var _f=window.fetch;
  window.fetch=function(u,o){
    if(typeof u==='string'&&(u.indexOf('/api/')===0||u.indexOf('/v1/')===0))u=B+u;
    return _f.call(this,u,o);
  };
  var _x=XMLHttpRequest.prototype.open;
  XMLHttpRequest.prototype.open=function(m,u){
    if(typeof u==='string'&&(u.indexOf('/api/')===0||u.indexOf('/v1/')===0))arguments[1]=B+u;
    return _x.apply(this,arguments);
  };
  try{__webpack_public_path__=B+'/';}catch(e){}
})();
</script>
`
	html = strings.Replace(html, "<script", basePathScript+"<script", 1)

	return []byte(html)
}

// manualRegisterImportExport manually registers import/export routes
// TODO: Remove this when IDL is regenerated with import/export definitions
func manualRegisterImportExport(r *server.Hertz) {
	api := r.Group("/api")
	workflowAPI := api.Group("/workflow_api")

	// Register import/export routes
	workflowAPI.POST("/export", cozeHandler.ExportWorkflow)
	workflowAPI.POST("/import", cozeHandler.ImportWorkflow)
	workflowAPI.POST("/validate_import", cozeHandler.ValidateImport)

}

func manualRegisterExternalKnowledge(r *server.Hertz) {
	api := r.Group("/api")
	externalKnowledgeGroup := api.Group("/external-knowledge")
	ragflowGroup := externalKnowledgeGroup.Group("/ragflow")
	ragflowGroup.POST("/datasets/create", external_knowledge_handler.CreateRAGFlowDataset)
	ragflowGroup.POST("/datasets/update", external_knowledge_handler.UpdateRAGFlowDataset)
	ragflowGroup.POST("/datasets/delete", external_knowledge_handler.DeleteRAGFlowDataset)
	ragflowGroup.GET("/session-key", external_knowledge_handler.GetRAGFlowSessionKey)

	knowledgeGroup := api.Group("/knowledge")
	knowledgeGroup.POST("/retrieve_test", cozeHandler.RetrieveTest)
}
