apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-server" (include "openynet.fullname" .) }}
  labels:
    {{- include "openynet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cozeServer.service.type }}
  ports:
  {{- range .Values.cozeServer.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: TCP
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "openynet.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: server
