/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/gorm"
)

const TableNameKnowledgeDocumentSlice = "knowledge_document_slice"

// KnowledgeDocumentSlice knowledge document slice
type KnowledgeDocumentSlice struct {
	ID          int64          `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`                                      // 主键ID
	KnowledgeID int64          `gorm:"column:knowledge_id;not null;comment:knowledge id" json:"knowledge_id"`            // knowledge id
	DocumentID  int64          `gorm:"column:document_id;not null;comment:document id" json:"document_id"`               // document id
	Content     string         `gorm:"column:content;comment:切片内容" json:"content"`                                       // 切片内容
	Sequence    float64        `gorm:"column:sequence;not null;type:decimal(20,5);comment:切片顺序号, 从1开始" json:"sequence"`  // 切片顺序号, 从1开始
	CreatedAt   int64          `gorm:"column:created_at;not null;comment:Create Time in Milliseconds" json:"created_at"` // Create Time in Milliseconds
	UpdatedAt   int64          `gorm:"column:updated_at;not null;comment:Update Time in Milliseconds" json:"updated_at"` // Update Time in Milliseconds
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;comment:Delete Time in Milliseconds" json:"deleted_at"`          // Delete Time in Milliseconds
	CreatorID   int64          `gorm:"column:creator_id;not null;comment:创建者ID" json:"creator_id"`                       // 创建者ID
	SpaceID     int64          `gorm:"column:space_id;not null;comment:空间ID" json:"space_id"`                            // 空间ID
	Status      int32          `gorm:"column:status;not null;comment:状态" json:"status"`                                  // 状态
	FailReason  string         `gorm:"column:fail_reason;comment:失败原因" json:"fail_reason"`                               // 失败原因
	Hit         int64          `gorm:"column:hit;not null;comment:命中次数" json:"hit"`                                      // 命中次数
}

// TableName KnowledgeDocumentSlice's table name
func (*KnowledgeDocumentSlice) TableName() string {
	return TableNameKnowledgeDocumentSlice
}
