/*
 * Copyright 2025 ynet-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package coze

import (
	"context"
	"strings"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	upload "github.com/ynet-dev/ynet-studio/backend/api/model/file/upload"
	uploadSVC "github.com/ynet-dev/ynet-studio/backend/application/upload"
	"github.com/ynet-dev/ynet-studio/backend/domain/plugin/conf"

	"github.com/ynet-dev/ynet-studio/backend/pkg/lang/ptr"
)

// CommonUpload .
// @router /api/common/upload/*tos_uri [POST]
func CommonUpload(ctx context.Context, c *app.RequestContext) {
	var err error
	var req upload.CommonUploadRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	fullUrl := string(c.Request.URI().FullURI())

	resp, err := uploadSVC.SVC.UploadFileCommon(ctx, &req, fullUrl)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// ApplyUploadAction .
// @router /api/common/upload/apply_upload_action [GET]
func ApplyUploadAction(ctx context.Context, c *app.RequestContext) {
	var err error
	var req upload.ApplyUploadActionRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(upload.ApplyUploadActionResponse)
	host := resolveUploadHost(
		conf.GetServerHost(),
		string(c.Host()),
		string(c.Request.Header.Peek("X-Forwarded-Host")),
	)
	if ptr.From(req.Action) == "ApplyImageUpload" {
		resp, err = uploadSVC.SVC.ApplyImageUpload(ctx, &req, host)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}
	} else if ptr.From(req.Action) == "CommitImageUpload" {
		resp, err = uploadSVC.SVC.CommitImageUpload(ctx, &req, host)
		if err != nil {
			internalServerErrorResponse(ctx, c, err)
			return
		}
	}

	c.JSON(consts.StatusOK, resp)
}

func resolveUploadHost(configuredHost, requestHost, forwardedHost string) string {
	configuredHost = normalizeUploadHost(configuredHost)
	requestHost = normalizeUploadHost(requestHost)
	forwardedHost = normalizeUploadHost(forwardedHost)

	externalHost := requestHost
	if forwardedHost != "" {
		externalHost = forwardedHost
	}

	if isLoopbackOrEmptyHost(configuredHost) && externalHost != "" {
		return externalHost
	}

	return configuredHost
}

func normalizeUploadHost(host string) string {
	host = strings.TrimSpace(host)
	if idx := strings.Index(host, ","); idx >= 0 {
		host = strings.TrimSpace(host[:idx])
	}
	host = strings.TrimPrefix(host, "http://")
	host = strings.TrimPrefix(host, "https://")
	return strings.TrimRight(host, "/")
}

func isLoopbackOrEmptyHost(host string) bool {
	if host == "" {
		return true
	}

	lowerHost := strings.ToLower(host)
	if idx := strings.LastIndex(lowerHost, ":"); idx > -1 && !strings.Contains(lowerHost[idx+1:], "]") {
		lowerHost = lowerHost[:idx]
	}
	lowerHost = strings.Trim(lowerHost, "[]")

	return lowerHost == "localhost" || lowerHost == "127.0.0.1" || lowerHost == "::1"
}
