/*
 * Copyright 2025 ynet-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator.

package space

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	spaceModel "github.com/ynet-dev/ynet-studio/backend/api/model/space"
	spaceApp "github.com/ynet-dev/ynet-studio/backend/application/space"
)

// ExportSpace exports a space to a ZIP package
// @router /api/space/{space_id}/export [POST]
func ExportSpace(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spaceModel.ExportSpaceRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := spaceApp.SpaceExportImportSVC.ExportSpace(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ImportPreview previews an import operation
// @router /api/space/{space_id}/import/preview [POST]
func ImportPreview(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spaceModel.ImportPreviewRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := spaceApp.SpaceExportImportSVC.ImportPreview(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ImportConfirm confirms and executes an import operation
// @router /api/space/{space_id}/import/confirm [POST]
func ImportConfirm(ctx context.Context, c *app.RequestContext) {
	var err error
	var req spaceModel.ImportConfirmRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp, err := spaceApp.SpaceExportImportSVC.ImportConfirm(ctx, &req)
	if err != nil {
		c.String(consts.StatusInternalServerError, err.Error())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
