// Code generated by hertz generator.

package admin

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"

	adminapi "github.com/coze-dev/coze-studio/backend/api/model/admin"
	adminapp "github.com/coze-dev/coze-studio/backend/application/admin"
	"github.com/coze-dev/coze-studio/backend/application/base/ctxutil"
	"github.com/coze-dev/coze-studio/backend/application/user"
	"github.com/coze-dev/coze-studio/backend/domain/user/entity"
)

// CheckAdminInit .
// @router /api/admin/check [GET]
func CheckAdminInit(ctx context.Context, c *app.RequestContext) {
	userIDPtr := ctxutil.GetUIDFromCtx(ctx)
	var userID uint64
	if userIDPtr != nil {
		userID = uint64(*userIDPtr)
	}

	resp, err := adminapp.AdminApplicationSVC.CheckAdminInit(ctx, userID)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// InitAdmin .
// @router /api/admin/init [POST]
func InitAdmin(ctx context.Context, c *app.RequestContext) {
	var req adminapi.InitAdminRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	// 如果没有传入 user_id，尝试从 session 获取当前登录用户的 ID
	if req.UserID == nil || *req.UserID == "" {
		// 先尝试从 context 获取（如果已经过认证中间件）
		userIDPtr := ctxutil.GetUIDFromCtx(ctx)
		if userIDPtr != nil && *userIDPtr > 0 {
			userIDStr := fmt.Sprintf("%d", *userIDPtr)
			req.UserID = &userIDStr
		} else {
			// 手动从 cookie 解析 session（因为此接口跳过了认证中间件）
			sessionKey := string(c.Cookie(entity.SessionKey))
			if sessionKey != "" {
				session, err := user.UserApplicationSVC.ValidateSession(ctx, sessionKey)
				if err == nil && session != nil && session.UserID > 0 {
					userIDStr := fmt.Sprintf("%d", session.UserID)
					req.UserID = &userIDStr
				}
			}
		}
	}

	resp, err := adminapp.AdminApplicationSVC.InitAdmin(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ListAdminUsers .
// @router /api/admin/users [GET]
func ListAdminUsers(ctx context.Context, c *app.RequestContext) {
	resp, err := adminapp.AdminApplicationSVC.ListAdminUsers(ctx)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// AddAdmin .
// @router /api/admin/users/add [POST]
func AddAdmin(ctx context.Context, c *app.RequestContext) {
	var req adminapi.AddAdminRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	operatorIDPtr := ctxutil.GetUIDFromCtx(ctx)
	var operatorID uint64
	if operatorIDPtr != nil {
		operatorID = uint64(*operatorIDPtr)
	}

	resp, err := adminapp.AdminApplicationSVC.AddAdmin(ctx, &req, operatorID)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// RemoveAdmin .
// @router /api/admin/users/remove [POST]
func RemoveAdmin(ctx context.Context, c *app.RequestContext) {
	var req adminapi.RemoveAdminRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	operatorIDPtr := ctxutil.GetUIDFromCtx(ctx)
	var operatorID uint64
	if operatorIDPtr != nil {
		operatorID = uint64(*operatorIDPtr)
	}

	resp, err := adminapp.AdminApplicationSVC.RemoveAdmin(ctx, &req, operatorID)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// ListPublicModels .
// @router /api/admin/models [GET]
func ListPublicModels(ctx context.Context, c *app.RequestContext) {
	var req adminapi.ListPublicModelsRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	resp, err := adminapp.AdminApplicationSVC.ListPublicModels(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// GetPublicModel .
// @router /api/admin/models/:model_id [GET]
func GetPublicModel(ctx context.Context, c *app.RequestContext) {
	var req adminapi.GetPublicModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	resp, err := adminapp.AdminApplicationSVC.GetPublicModel(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// CreatePublicModel .
// @router /api/admin/models/create [POST]
func CreatePublicModel(ctx context.Context, c *app.RequestContext) {
	var req adminapi.CreatePublicModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	resp, err := adminapp.AdminApplicationSVC.CreatePublicModel(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// UpdatePublicModel .
// @router /api/admin/models/:model_id/update [POST]
func UpdatePublicModel(ctx context.Context, c *app.RequestContext) {
	var req adminapi.UpdatePublicModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	resp, err := adminapp.AdminApplicationSVC.UpdatePublicModel(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// DeletePublicModel .
// @router /api/admin/models/delete [POST]
func DeletePublicModel(ctx context.Context, c *app.RequestContext) {
	var req adminapi.DeletePublicModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	resp, err := adminapp.AdminApplicationSVC.DeletePublicModel(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// EnablePublicModel .
// @router /api/admin/models/enable [POST]
func EnablePublicModel(ctx context.Context, c *app.RequestContext) {
	var req adminapi.EnablePublicModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	resp, err := adminapp.AdminApplicationSVC.EnablePublicModel(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// DisablePublicModel .
// @router /api/admin/models/disable [POST]
func DisablePublicModel(ctx context.Context, c *app.RequestContext) {
	var req adminapi.DisablePublicModelRequest
	if err := c.BindAndValidate(&req); err != nil {
		c.JSON(consts.StatusBadRequest, utils.H{"code": 400, "msg": err.Error()})
		return
	}

	resp, err := adminapp.AdminApplicationSVC.DisablePublicModel(ctx, &req)
	if err != nil {
		c.JSON(consts.StatusInternalServerError, utils.H{"code": 500, "msg": err.Error()})
		return
	}

	c.JSON(consts.StatusOK, resp)
}
