// Code generated by hertz generator. DO NOT EDIT.

package space

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	space "github.com/coze-dev/coze-studio/backend/api/handler/space"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// RegisterExportImport register routes based on the IDL 'api.${HTTP Method}' annotation.
func RegisterExportImport(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_space := _api.Group("/space", _spaceMw()...)
			{
				__7bspace_id_7d := _space.Group("/:space_id", __7bspace_id_7dMw()...)
				__7bspace_id_7d.POST("/export", append(_exportspaceMw(), space.ExportSpace)...)
				{
					_import := __7bspace_id_7d.Group("/import", _importMw()...)
					_import.POST("/confirm", append(_importconfirmMw(), space.ImportConfirm)...)
					_import.POST("/preview", append(_importpreviewMw(), space.ImportPreview)...)
				}
			}
		}
	}
}
