/*
 * Copyright 2025 ynet-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by hertz generator. DO NOT EDIT.

package space

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	space "github.com/ynet-dev/ynet-studio/backend/api/handler/space"
)

/*
 This file will register all the routes of the services in the master idl.
 And it will update automatically when you use the "update" command for the idl.
 So don't modify the contents of the file, or your code will be deleted when it is updated.
*/

// Register register routes based on the IDL 'api.${HTTP Method}' annotation.
func Register(r *server.Hertz) {

	root := r.Group("/", rootMw()...)
	{
		_api := root.Group("/api", _apiMw()...)
		{
			_space := _api.Group("/space", _spaceMw()...)
			_space.POST("/create", append(_createspaceMw(), space.CreateSpace)...)
			_space.GET("/list", append(_getspacelistMw(), space.GetSpaceList)...)
			_space.GET("/search-users", append(_searchusersMw(), space.SearchUsers)...)
			_space.DELETE("/:space_id", append(_deletespaceMw(), space.DeleteSpace)...)
			__7bspace_id_7d := _space.Group("/:space_id", __7bspace_id_7dMw()...)
			__7bspace_id_7d.GET("/members", append(_getspacemembersMw(), space.GetSpaceMembers)...)
			_members := __7bspace_id_7d.Group("/members", _membersMw()...)
			_members.DELETE("/:user_id", append(_removememberMw(), space.RemoveMember)...)
			_members.PUT("/:user_id", append(_updatememberroleMw(), space.UpdateMemberRole)...)
			__7bspace_id_7d.POST("/members", append(_invitememberMw(), space.InviteMember)...)
			__7bspace_id_7d.GET("/permission", append(_checkmemberpermissionMw(), space.CheckMemberPermission)...)
			__7bspace_id_7d.POST("/transfer", append(_transferspaceMw(), space.TransferSpace)...)
			_space.GET("/:space_id", append(_getspacedetailMw(), space.GetSpaceDetail)...)
			_space.PUT("/:space_id", append(_updatespaceMw(), space.UpdateSpace)...)
		}
	}
}
